pipeline {

    agent any

    environment {
        APP_NAME = "my-app"
        DOCKER_IMAGE = "my-app_image"
    }
    stages {
        stage('Checkout Code'){
            steps {
                git branch: 'main', url: 'https://github.com/org/repo.git'
            }
        }
        stage("Build"){
            steps {
                sh " echo  Building application....."
                sh "mvn clean package!"
            }
        }
        stage('Unit Tests'){
            steps {
                sh 'echo Running tests...'
                sh 'mvn test'
            }
        }
        stage('Code Quality') {
            steps {
                sh 'echo Runnig SonarQube scan'
                sh 'echo sonar:sonar'
            }
        }
        stage ('Docker Build') {
            steps {
                sh 'docker build -t  $DOCKER_IMAGE .'
            }
        }
        stage ('Push Image') {
            steps {
                sh 'docker tag $ DOCKER_IMAGE repo/ $DOCKER_IMAGE'
                sh 'docker push repo/$DOCKER_IMAGE'
            }
        }
        stage ('Deploy'){
            steps {
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
        always {
            cleanWs()
        }
    }

}